# Generated by Django 2.0.5 on 2018-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
