# Generated by Django 2.0.5 on 2018-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0003_auto_20180601_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseprocess',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
