# Generated by Django 2.0.5 on 2018-06-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0004_purchaseprocess_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseprocess',
            name='description',
        ),
    ]
