# Generated by Django 2.0.5 on 2018-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0007_auto_20180604_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='manager_approved',
            field=models.BooleanField(verbose_name='Approved'),
        ),
    ]
