# Generated by Django 2.0.5 on 2018-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0008_auto_20180604_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='manager_approved',
            field=models.NullBooleanField(choices=[(None, ' '), (True, 'Yes'), (False, 'No')], verbose_name='Approved'),
        ),
    ]
