# Generated by Django 2.0.5 on 2018-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0013_auto_20180605_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='manager_approved',
            field=models.NullBooleanField(choices=[(None, 'Not Decided'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='need_price_quote',
            field=models.NullBooleanField(choices=[(None, 'Not Decided'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_team_comment',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
