# Generated by Django 2.0.5 on 2018-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0015_purchase_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='support_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
