# Generated by Django 2.0.5 on 2018-06-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0016_purchase_support_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='support_user',
        ),
    ]
