# Generated by Django 2.0.5 on 2018-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0017_remove_purchase_support_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_user',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='purchase',
            name='support_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
