# Generated by Django 2.0.5 on 2018-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0018_auto_20180606_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_team_investigator',
            field=models.CharField(default='', max_length=500),
        ),
    ]
