# Generated by Django 2.0.5 on 2018-06-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0019_purchase_purchase_team_investigator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='manager_approved',
            new_name='manager_approval',
        ),
    ]
