# Generated by Django 2.0.5 on 2018-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0022_auto_20180606_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_quoted',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
