# Generated by Django 2.0.5 on 2018-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0023_auto_20180606_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='investigator_comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
