# Generated by Django 2.0.5 on 2018-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0024_purchase_investigator_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='need_price_quote',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
