# Generated by Django 2.0.5 on 2018-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0026_auto_20180606_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='need_price_quote',
            field=models.NullBooleanField(choices=[(None, 'Not Decided'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_quoted',
            field=models.FloatField(default=0.0),
        ),
    ]
