# Generated by Django 2.0.5 on 2018-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0027_auto_20180606_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_quoted',
            field=models.FloatField(),
        ),
    ]
