# Generated by Django 2.0.5 on 2018-06-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0029_auto_20180607_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='manager_approval',
            field=models.NullBooleanField(choices=[('Not Decided', 'Not Decided'), ('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='need_price_quote',
            field=models.CharField(choices=[('Not Decided', 'Not Decided'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=500),
            preserve_default=False,
        ),
    ]
