# Generated by Django 2.0.5 on 2018-06-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0031_auto_20180607_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_team_investigator',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='support_user',
        ),
    ]
