# Generated by Django 2.0.5 on 2018-06-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0032_auto_20180607_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='manager_approval',
            new_name='superior_approval',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='manager_comment',
            new_name='superior_comment',
        ),
    ]
