# Generated by Django 2.0.5 on 2018-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0034_purchase_support_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency_quoted',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='need_price_quote',
            field=models.CharField(choices=[('None', 'Not Decided'), ('Yes', 'Yes'), ('No', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='superior_approval',
            field=models.CharField(blank=True, choices=[('None', 'Not Decided'), ('Yes', 'Yes'), ('No', 'No')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='support_approval',
            field=models.CharField(blank=True, choices=[('None', 'Not Decided'), ('Yes', 'Yes'), ('No', 'No')], max_length=500, null=True),
        ),
    ]
