# Generated by Django 2.0.5 on 2018-06-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_purchase_app', '0038_auto_20180612_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'purchase', 'verbose_name_plural': 'purchases'},
        ),
    ]
