PERSONAL_LIMIT_FOR_DEVELOPER = 100
PERSONAL_LIMIT_FOR_MANAGER = 1000
PERSONAL_LIMIT_FOR_DIRECTOR = 10000
PERSONAL_LIMIT_FOR_GENERAL_MANAGER = 100000

DEVELOPER_TITLE = 'developer'
MANAGER_TITLE = 'manager'
DIRECTOR_TITLE = 'director'
GENERAL_MANAGER_TITLE = 'general_manager'
CEO_TITLE = 'ceo'

PERMISSION_ALWAYS_GRANTED_GROUPS = [CEO_TITLE]

PERSONAL_LIMITS = {
    DEVELOPER_TITLE: PERSONAL_LIMIT_FOR_DEVELOPER,
    MANAGER_TITLE: PERSONAL_LIMIT_FOR_MANAGER,
    DIRECTOR_TITLE: PERSONAL_LIMIT_FOR_DIRECTOR,
    GENERAL_MANAGER_TITLE: PERSONAL_LIMIT_FOR_GENERAL_MANAGER,
}

TITLES_WEIGHT = {
    DEVELOPER_TITLE: 5,
    MANAGER_TITLE: 4,
    DIRECTOR_TITLE: 3,
    GENERAL_MANAGER_TITLE: 2,
    CEO_TITLE: 1,
}
