# Generated by Django 2.0.5 on 2018-05-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_approve_purchase', 'Can approve it_purchase_app form'), ('can_create_purchase', 'Can create it_purchase_app form'), ('can_support_purchase', 'Can support it_purchase_app form')]},
        ),
    ]
