# Generated by Django 2.0.5 on 2018-06-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180601_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_approve_purchase', 'Can approve it_purchase_app form'), ('can_create_purchase', 'Can create it_purchase_app form'), ('can_support_purchase', 'Can support it_purchase_app form'), ('can_purchase_team', 'Can get price quote it_purchase_app form')]},
        ),
    ]
